### PR TITLE
Stop Conformity Monkey on destroy

### PR DESCRIPTION
**Pull request by mlafeldt**
In addition to the other monkeys.

### CODE REVIEW

**Comment by mlafeldt** [comment]
PTAL.

Related question: why does the Simian Army start/stop *all* the monkeys, even if they're disabled via properties. I found this to be a bit confusing when first using the app, especially since the scheduler keeps logging that it's not time for monkey X even though X has been disabled.

**Comment by ebukoski** [comment]
That is a good question, I've wondered that myself.  I would agree that if a monkey is disabled it would be better to not see any messages from it.

My theory about why they are started/stopped even if disabled: internally at Netflix the properties class is replaced with a Netflix internal realtime distributed property system.  It gives us the ability to change any property from a central location and have the changes reflected in real time in any app including SimianArmy.  So in theory we could enable/disable a monkey instantly with a property change but it would only work if the Monkey was enabled/started in the first place.  However in reality we never do this so it is a purely theoretical capability.

**Comment by ebukoski** [comment]
PR LGTM thanks for the contribution!

**Comment by mlafeldt** [comment]
> internally at Netflix the properties class is replaced with a Netflix internal realtime distributed property system

@ebukoski OK, in that context the code makes sense. Thanks for the detailed explanation.

**Pull request merged**
